mail/dovecot 0.99.10
  o Synchronise README.FreeBSD with current reality.
  o Improve security a little by adding a 'dovecot-auth'
    user and group.

PR:		53875
Submitted by:	Dominic Marks <dominic.marks@btinternet.com> (maintainer)

diff --git a/mail/dovecot/pkg-install b/mail/dovecot/pkg-install
--- a/mail/dovecot/pkg-install
+++ b/mail/dovecot/pkg-install
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#	$FreeBSD: ports/mail/dovecot/pkg-install,v 1.1 2002/09/01 14:17:04 vanilla Exp $
+#	$FreeBSD: ports/mail/dovecot/pkg-install,v 1.2 2003/05/03 21:50:26 nork Exp $
 #
 
 PKG_PREFIX=${PKG_PREFIX:=/usr/local}
@@ -52,7 +52,7 @@ if [ x"$2" = xPRE-INSTALL ]; then
         fi
     fi
 
-    if /usr/sbin/pw user show "${USER}" 2>/dev/null; then
+    if /usr/sbin/pw usershow "${USER}" 2>/dev/null; then
         echo "You already have a user \"${USER}\", so I will use it."
     else
         if /usr/sbin/pw useradd ${USER} -g ${GROUP} -h - \
@@ -67,4 +67,34 @@ if [ x"$2" = xPRE-INSTALL ]; then
         fi
     fi
 
+    USER=dovecot-auth
+    GROUP=dovecot-auth
+
+    if /usr/sbin/pw groupshow "${GROUP}" 2>/dev/null; then
+	echo "You already have a group \"${GROUP}\", so I will use it."
+    else
+	if /usr/sbin/pw groupadd ${GROUP} -h -
+	then
+	    echo "Added group \"${GROUP}\"."
+	else
+	    echo "Adding group \"${GROUP}\" failed..."
+	    echo "Please create it, and try again."
+	    exit 1
+        fi
+    fi
+
+    if /usr/sbin/pw usershow "${USER}" 2>/dev/null; then
+	echo "You already have a user \"${USER}\", so I will use it."
+    else
+	if /usr/sbin/pw useradd ${USER} -g ${GROUP} -h - \
+	   -s /sbin/nologin \
+	   -c "Dovecot Auth"
+        then
+	    echo "Added user \"${USER}\"."
+	else
+	    echo "Adding user \"${USER}\" failed..."
+	    echo "Please create it, and try again."
+	    exit 1
+        fi
+    fi
 fi
