- Update to 20080520 - Change OPTION UNRAR on by default to align with clamav port - USE_GMAKE to build fine new version

diff --git a/security/clamav-devel/files/clamav-clamd.in b/security/clamav-devel/files/clamav-clamd.in
--- a/security/clamav-devel/files/clamav-clamd.in
+++ b/security/clamav-devel/files/clamav-clamd.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD$
+# $FreeBSD: ports/security/clamav-devel/files/clamav-clamd.in,v 1.1 2006/04/07 10:10:20 garga Exp $
 #
 
 # PROVIDE: clamd
@@ -31,5 +31,14 @@ load_rc_config "$name"
 : ${clamav_clamd_enable="NO"}
 : ${clamav_clamd_flags=""}
 : ${clamav_clamd_socket="%%CLAMAV_CLAMD_SOCKET%%"}
+
+start_precmd=clamav_clamd_precmd
+
+clamav_clamd_precmd() {
+	if [ ! -f %%DBDIR%%/main.cvd ];then
+		echo "Missing %%DBDIR%%/clamav/*.cvd files.  You must run freshclam first"
+		exit 1
+	fi
+}
 
 run_rc_command "$1"
