Make this port add shell to cyrus user.
PR:		ports/38436
Submitted by:	Scot W. Hetzel <hetzels@westbend.net>

diff --git a/mail/cyrus-imapd2/pkg-deinstall b/mail/cyrus-imapd2/pkg-deinstall
--- a/mail/cyrus-imapd2/pkg-deinstall
+++ b/mail/cyrus-imapd2/pkg-deinstall
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#	$FreeBSD: ports/mail/cyrus-imapd/pkg-deinstall,v 1.1 2000/12/21 08:25:47 will Exp $
+#	$FreeBSD: ports/mail/cyrus-imapd/pkg-deinstall,v 1.2 2001/03/13 11:15:09 ume Exp $
 #
 # Created by: hetzels@westbend.net
 
@@ -35,6 +35,28 @@ cyrus_conf() {
 	fi
 }
 
+#
+# Modify the 'cyrus' user created from the cyrus-sasl port
+#
+
+modify_cyrus_user() {
+	USER=cyrus
+	PW=/usr/sbin/pw
+	if [ -x /sbin/nologin ]; then
+		shell=/sbin/nologin
+	else
+		shell=/nonexistent
+	fi
+	uhome=/nonexistent
+
+	if ! ${PW} mod user ${USER} -d "${uhome}" -s "${shell}" \ ; then
+		e=$?
+		echo "*** Failed to update user \`${USER}'."
+		exit ${e}
+	fi
+	echo "*** Updated user \`${USER}'."
+}
+
 case $2 in
 	DEINSTALL)
 		cd ${PKG_PREFIX}
@@ -43,6 +65,7 @@ case $2 in
 		checkfile ${PKG_PREIFX}/etc/cyrus.conf
 		;;
 	POST-DEINSTALL)
+		modify_cyrus_user
 		;;
 
 esac
