- Correctly define dependency - For FreeBSD 6.X and later - Correctly preserve index.html - Remove user and group left behind at deinstall
PR:		ports/117003
Submitted by:	Dan Voisine <voisined@wit.edu> (maintainer)

diff --git a/www/abyssws/pkg-install b/www/abyssws/pkg-install
--- a/www/abyssws/pkg-install
+++ b/www/abyssws/pkg-install
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# $FreeBSD: ports/www/abyssws/pkg-install,v 1.1 2007/09/06 12:00:07 edwin Exp $
+# $FreeBSD: ports/www/abyssws/pkg-install,v 1.2 2007/09/15 09:16:59 beech Exp $
 
 PATH=/bin:/usr/sbin
 WSHOME=${PKG_PREFIX}/lib/abyssws
@@ -39,10 +39,7 @@ PRE-INSTALL)
 		chown ${USER}:${GROUP} ${WSHOME}
 	fi
 
-	if [ -r ${WSHOME}/htdocs/index.html ] ; then
-	       mv ${WSHOME}/htdocs/index.html ${WSHOME}/htdocs/index.html.bak
-	fi
-
+	
 	;;
 
 POST-INSTALL)
@@ -50,11 +47,32 @@ POST-INSTALL)
 	chmod -R u+w,o-rx ${WSHOME}
 	chmod u+s ${WSHOME}/abyssws
 	
-	if [ -r ${WSHOME}/htdocs/index.html.bak ] ; then
-	       mv ${WSHOME}/htdocs/index.html.bak ${WSHOME}/htdocs/index.html
-	fi
-
+	
 	;;
+POST-DEINSTALL)
+	if ! [ -x ${WSHOME} ] ; then
+	    if pw group show "${GROUP}" 2>/dev/null; then
+		if pw groupdel ${GROUP}; then
+		    echo "Removed group \"${GROUP}\"."
+		else
+		    echo "Removing group \"${GROUP}\" failed..."
+		    exit 1
+		fi
+	    else
+		echo "Group \"${GROUP}\" doesn't exist!"
+	    fi
 
+	    if pw user show "${USER}" 2>/dev/null; then
+		if pw userdel ${USER}; then
+		    echo "Removed user \"${USER}\"."
+		else
+		    echo "Removing user \"${USER}\" failed..."
+		    exit 1
+		fi
+	    else
+		echo "User \"${USER}\" doesn't exist!"
+	    fi
+	fi
+	;;
 
 esac
