- Chase checksum for sasl-1.5.27-ldap-ssl-filter-mysql-patch4.tgz   author fixed bug in patch but didn't increment version. - Fix problem when openldap v1 is selected. - Bump PORTREVISION
PR:		ports/39800
Submitted by:	maintainer

diff --git a/security/cyrus-sasl2/pkg-install b/security/cyrus-sasl2/pkg-install
--- a/security/cyrus-sasl2/pkg-install
+++ b/security/cyrus-sasl2/pkg-install
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#	$FreeBSD: ports/security/cyrus-sasl/pkg-install,v 1.7 2002/05/21 15:08:58 dwcjr Exp $
+#	$FreeBSD: ports/security/cyrus-sasl/pkg-install,v 1.8 2002/05/24 02:01:13 dwcjr Exp $
 #
 # Created by: stb@FreeBSD.org for the cyrus imap server
 # Added to the cyrus-sasl port by hetzels@westbend.net
@@ -67,9 +67,12 @@ create_user() {
 		fi
 		echo "*** Updated user \`${USER}'."
 	fi
-	if ! ${PW} group mod ${USER} -m daemon; then
-		echo "*** can't add user \`${USER}' to group \`${GROUP}'"
-	fi
+# Don't know why we need the daemon user in the cyrus group
+# hopefully this doesn't affect anyone. It's a leftover from
+# the pre-SASL cyrus-imapd server.
+#	if ! ${PW} group mod ${GROUP} -m daemon; then
+#		echo "*** can't add user \`daemon' to group \`${GROUP}'"
+#	fi
 }
 
 create_sasldb() {
