Revert previous commit -- appears to cause rc problems as I missed some subs
http://www.mail-archive.com/freebsd-ports@freebsd.org/msg35324.html

PR:		ports/157558 ports/157559 ports/157666 ports/157669
Submitted by:	rihad@mail.ru
Approved by:	maintainer (girgen; implicit -- this reverts a commit I did after maintainer timeout)

diff --git a/databases/postgresql82-server/pkg-install-server b/databases/postgresql82-server/pkg-install-server
--- a/databases/postgresql82-server/pkg-install-server
+++ b/databases/postgresql82-server/pkg-install-server
@@ -1,8 +1,10 @@
 #! /bin/sh
 
-# $FreeBSD: ports/databases/postgresql82-server/pkg-install-server,v 1.2 2006/12/06 16:48:57 girgen Exp $
+# $FreeBSD$
 
 PATH=/bin:/usr/sbin
+PGUSER=pgsql
+DB_DIR=${PKG_PREFIX}/${PGUSER}
 
 backupwarning() { echo "
 
@@ -20,6 +22,43 @@ backupwarning() { echo "
 }
 
 case $2 in
+PRE-INSTALL)
+	backupwarning
+	USER=${PGUSER}
+	GROUP=${USER}
+	UID=70
+	GID=${UID}
+
+	if pw group show "${GROUP}" 2>/dev/null; then
+		echo "You already have a group \"${GROUP}\", so I will use it."
+	else
+		if pw groupadd ${GROUP} -g ${GID}; then
+			echo "Added group \"${GROUP}\"."
+		else
+			echo "Adding group \"${GROUP}\" failed..."
+			exit 1
+		fi
+	fi
+
+	if pw user show "${USER}" 2>/dev/null; then
+		echo "You already have a user \"${USER}\", so I will use it."
+	else
+		if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
+			-d ${DB_DIR} -c "PostgreSQL Daemon"
+		then
+			echo "Added user \"${USER}\"."
+		else
+			echo "Adding user \"${USER}\" failed..."
+			exit 1
+		fi
+	fi
+
+	if ! [ -x ~${PGUSER} ] ; then 
+		mkdir -p ${DB_DIR}
+		chown pgsql:pgsql ${DB_DIR}
+	fi
+	;;
+
 BACKUPWARNING)
 	backupwarning
 	;;
