Add some missing error handling.

diff --git a/Tools/portbuild/scripts/dopackages b/Tools/portbuild/scripts/dopackages
--- a/Tools/portbuild/scripts/dopackages
+++ b/Tools/portbuild/scripts/dopackages
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $FreeBSD: ports/Tools/portbuild/scripts/dopackages,v 1.54 2010/06/25 23:14:13 linimon Exp $
+# $FreeBSD$
 
 # main server-side script to run a package build
 
@@ -237,6 +237,10 @@ dobuild() {
     echo "started at $(date)"
     start=$(date +%s)
     ${QMANAGER_PATH}/packagebuild ${arch} ${branch} ${buildid} > ${builddir}/${journalname} 2>&1 < /dev/null
+    result=$?
+    if [ $result -ne 0 ]; then
+        echo "ERROR: packagebuild ${arch} ${branch} ${buildid} failed: see ${builddir}/${journalname} for details"
+    fi
     echo "ended at $(date)"
     end=$(date +%s)
     echo "Build took $(date -u -j -r $((end - start)) | awk '{print $4}')"
